/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'chatMessage': MotiaStream<{ message: string; sender: string; timestamp: string }>
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'UserRegistrationAPI': ApiRouteHandler<{ username: string }, unknown, never>
    'getUserRooms': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'getRoomid-API': ApiRouteHandler<{ roomID: string; userId: string }, unknown, never>
    'delete-Room-API': ApiRouteHandler<{ roomID: string; userId: string }, unknown, never>
    'create-Room-API': ApiRouteHandler<{ roomName: string; userId: string }, unknown, never>
    'clearChatRoom': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'chatMessage': ApiRouteHandler<{ message: string; sender: string; timestamp: string }, unknown, never>
  }
    interface StreamAuthContext { userId: string; allowedRooms: Array<string> }
}